---
# tasks file for node
- name: Check node is installed
  become: yes
  stat:
    path: "{{ node_bin_path }}"
  register: bin_node

- name: Install nodejs
  become: yes
  when: not bin_node.stat.exists
  block:
    - name: "Install leaked dependent packages"
      apt:
        name:
          - nodejs-dev
          - node-gyp
          - libssl1.0-dev
        state: present
    - name: Install standard nodejs and npm
      apt:
        name:
          - nodejs
          - npm
        state: present
    - name: Install standard nodejs and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Clean cache
      shell: npm cache clean

    - name: Install n on global
      shell: npm install -g n

    - name: Install specific version node
      shell: "n {{ node_install_version }}"

    - name: Remove old node and npm
      apt:
        name:
          - nodejs
          - npm
        purge: yes
        state: absent
