---
# tasks file for node
- name: Check node is installed
  become: yes
  stat:
    path: "{{ node_bin_path }}"
  register: bin_node

- name: Install nodejs
  become: yes
  when: not bin_node.stat.exists
  block:
    - name: Install standard nodejs and npm
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nodejs
        - npm

    - name: Clean cache
      shell: npm cache clean

    - name: Install n on global
      shell: npm install -g n

    - name: Install specific version node
      shell: "n {{ node_install_version }}"

    - name: Remove old node and npm
      apt:
        name: "{{ item }}"
        purge: yes
        state: absent
      with_items:
        - nodejs
        - npm
